refactor and add debug flag for command line.

diff --git a/.cfg/functions b/.cfg/functions
--- a/.cfg/functions
+++ b/.cfg/functions
@@ -1,4 +1,7 @@
 #!/bin/bash
+# set -o errexit
+set -o nounset
+set -o pipefail
 # The next incarnation will use a git repo pulled into the
 # jenkins home
 
@@ -26,15 +29,13 @@ check
 mkdir -p ${dir}/.cfg  ${dir}/.private
 chmod 700 ${dir} ${dir}/.cfg ${dir}/.private
 
-if [[ ! -e ${dir}/.cfg ]]; then
-    echo Unconfigured options directory .cfg
+if [[ ! -e ${dir}/.cfg/options ]]; then
+    echo Unconfigured options [.cfg/options]
     exit 3
 fi
 
 . ${dir}/.cfg/options
 
-# defer evaluation of the directory variable /go/home/k8s/jenkins is
-# to enable location independence.
 if ! [[ -e ${kubeconfig} ]]; then
     printf "k8s username: ";
     read -r username
@@ -51,9 +52,19 @@ if ! [[ -e ${kubeconfig} ]]; then
 fi
 
 export kubectl="${kubectl} --kubeconfig=${kubeconfig}"
+if [[ -e ${make_yaml_file} ]]; then
+    . ${make_yaml_file}
+fi
+if [[ ! -e ${make_yaml_file} || ! ${make-yaml:-} ]]; then
+    echo "Required function make-yaml is not defined"
+    echo "It's simplest form could be cat of the yaml file."
+    echo "Any function that dumps the yaml on stdout, such as a sed stream edit may also be used."
+    exit 3
+fi
 
 function start
 {
+    generate
     ${kubectl} create -f- <<EOF
 $(make-yaml)
 EOF
@@ -73,7 +84,7 @@ function status
     ${kubectl} get --all-namespaces --output=wide rc,pods,svc,ep
 }
 
-function main
+function generate
 {
     rm -f ${yaml}
     if (( debug )); then
@@ -83,10 +94,26 @@ function main
         fi
         chmod 600 ${yaml}
     fi
+}
 
+function main
+{
     if (( $# )) ; then
+        # set flags prior to calling any methods
         for arg in ${@}; do
             case ${arg} in
+                --debug)
+                    debug=1
+                    ;;
+                --verbose)
+                    verbose=1
+                    ;;
+            esac
+        done
+        for arg in ${@}; do
+            case ${arg} in
+                --debug|--verbose) # ignore these, don't generate a usage call
+                    ;;
                 --start)
                     start
                     ;;
diff --git a/.cfg/options b/.cfg/options
--- a/.cfg/options
+++ b/.cfg/options
@@ -5,13 +5,14 @@
 # master /etc/host entry or DNS entry for access host to k8s cluster
 # os_user user on the os on the k8s nodes.
 
-prefix=dw
-ssh_key_type=rsa
-master=k8s-dw-master-01
-os_user=centos
-name=${dir##*/}
-yaml=${dir}/${name}.yaml
-inyaml=${dir}/${name}-template.yaml
+mycfg=${dir}/.cfg/mycfg
+
+if [[ ! -e ${mycfg:-} ]]; then
+    echo "${mycfg} was not found. have you tailored the configuration to your requirements?"
+    exit 3
+fi
+
+. ${dir}/.cfg/mycfg
 
 function validate
 {
@@ -34,6 +35,10 @@ validate os_user
 validate name
 validate yaml
 validate inyaml
+validate make_yaml_file
+validate hubuid
+validate k8srepo
+validate hubrepo
 
 export kubectl=${dir}/bin/kubectl
 export kubeconfig=${dir}/.private/.${master}.cfg
